=== katydid/paper-2027-mem-filter-benchmarks-jsonschema/schemas/draft-04-noUniqueItems/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Core schema meta-schema",
  "definitions": {
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#"
      }
    },
    "positiveInteger": {
      "type": "integer",
      "minimum": 0
    },
    "positiveIntegerDefault0": {
      "allOf": [
        {
          "$ref": "#/definitions/positiveInteger"
        },
        {
          "default": 0
        }
      ]
    },
    "simpleTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "stringArray": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "default": true,
    "multipleOf": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "maximum": {
      "type": "number"
    },
    "exclusiveMaximum": {
      "type": "boolean",
      "default": false
    },
    "minimum": {
      "type": "number"
    },
    "exclusiveMinimum": {
      "type": "boolean",
      "default": false
    },
    "maxLength": {
      "$ref": "#/definitions/positiveInteger"
    },
    "minLength": {
      "$ref": "#/definitions/positiveIntegerDefault0"
    },
    "pattern": {
      "type": "string",
      "format": "regex"
    },
    "additionalItems": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "$ref": "#"
        }
      ],
      "default": {}
    },
    "items": {
      "anyOf": [
        {
          "$ref": "#"
        },
        {
          "$ref": "#/definitions/schemaArray"
        }
      ],
      "default": {}
    },
    "maxItems": {
      "$ref": "#/definitions/positiveInteger"
    },
    "minItems": {
      "$ref": "#/definitions/positiveIntegerDefault0"
    },
    "uniqueItems": {
      "type": "boolean",
      "default": false
    },
    "maxProperties": {
      "$ref": "#/definitions/positiveInteger"
    },
    "minProperties": {
      "$ref": "#/definitions/positiveIntegerDefault0"
    },
    "required": {
      "$ref": "#/definitions/stringArray"
    },
    "additionalProperties": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "$ref": "#"
        }
      ],
      "default": {}
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "properties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "patternProperties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "anyOf": [
          {
            "$ref": "#"
          },
          {
            "$ref": "#/definitions/stringArray"
          }
        ]
      }
    },
    "enum": {
      "type": "array",
      "minItems": 1
    },
    "type": {
      "anyOf": [
        {
          "$ref": "#/definitions/simpleTypes"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/simpleTypes"
          },
          "minItems": 1
        }
      ]
    },
    "format": {
      "type": "string"
    },
    "allOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "anyOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "oneOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "not": {
      "$ref": "#"
    }
  },
  "dependencies": {
    "exclusiveMaximum": [
      "maximum"
    ],
    "exclusiveMinimum": [
      "minimum"
    ]
  },
  "default": {},
  "$id": "http://json-schema.org/draft-04/schema#"
}

=== katydid/paper-2027-mem-filter-benchmarks-jsonschema/schemas/ajv-complex/schema.json
{
      "type": "array",
      "items": {"$ref": "#transaction"},
      "minItems": 1,
      "definitions": {
        "base58": {
          "$anchor": "base58",
          "type": "string",
          "pattern": "^[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]+$"
        },
        "hex": {
          "$anchor": "hex",
          "type": "string",
          "pattern": "^[0123456789A-Fa-f]+$"
        },
        "tx_id": {
          "$anchor": "tx_id",
          "allOf": [
            {"$ref": "#hex"},
            {
              "minLength": 64,
              "maxLength": 64
            }
          ]
        },
        "address": {
          "$anchor": "address",
          "allOf": [
            {"$ref": "#base58"},
            {
              "minLength": 34,
              "maxLength": 34
            }
          ]
        },
        "signature": {
          "$anchor": "signature",
          "allOf": [
            {"$ref": "#hex"},
            {
              "minLength": 128,
              "maxLength": 128
            }
          ]
        },
        "transaction": {
          "$anchor": "transaction",
          "additionalProperties": false,
          "required": ["metadata", "hash", "inputs", "outputs"],
          "properties": {
            "metadata": {
              "type": "object",
              "required": ["amount", "fee"],
              "properties": {
                "amount": {
                  "type": "integer"
                },
                "fee": {
                  "type": "integer",
                  "multipleOf": 10000
                },
                "status": {
                  "type": "string",
                  "enum": ["unsigned", "unconfirmed", "confirmed", "invalid"]
                },
                "confirmations": {
                  "type": "integer",
                  "minimum": 0
                },
                "block_time": {
                  "type": "integer"
                }
              }
            },
            "version": {
              "type": "integer"
            },
            "lock_time": {
              "type": "integer"
            },
            "hash": {"$ref": "#tx_id"},
            "inputs": {
              "type": "array",
              "items": {"$ref": "#input"},
              "minItems": 1
            },
            "outputs": {
              "type": "array",
              "items": {"$ref": "#output"},
              "minItems": 1
            }
          }
        },
        "input": {
          "$anchor": "input",
          "type": "object",
          "additionalProperties": false,
          "required": ["index", "output", "script_sig"],
          "properties": {
            "index": {
              "type": "integer",
              "minimum": 0
            },
            "output": {"$ref": "#output"},
            "sig_hash": {"$ref": "#hex"},
            "script_sig": {"$ref": "#hex"},
            "signatures": {
              "type": "object",
              "description": "A dictionary of signatures.  Keys represent keypair names",
              "minProperties": 1,
              "maxProperties": 3,
              "additionalProperties": {"$ref": "#signature"}
            }
          }
        },
        "output": {
          "$anchor": "output",
          "type": "object",
          "additionalProperties": false,
          "required": ["hash", "index", "value", "script"],
          "properties": {
            "hash": {"$ref": "#tx_id"},
            "index": {
              "type": "integer",
              "minimum": 0
            },
            "value": {
              "type": "integer"
            },
            "script": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": ["standard", "p2sh"]
                },
                "asm": {
                  "type": "string"
                }
              }
            },
            "address": {"$ref": "#address"},
            "metadata": {
              "type": "object",
              "dependentRequired": {
                "wallet_path": ["public_seeds"]
              },
              "properties": {
                "wallet_path": {
                  "type": "string"
                },
                "public_seeds": {
                  "type": "object",
                  "minProperties": 1,
                  "maxProperties": 3,
                  "additionalProperties": {
                    "anyOf": [{"$ref": "#base58"}, {"$ref": "#hex"}]
                  }
                }
              }
            }
          }
        }
      }
	}

=== katydid/paper-2027-mem-filter-benchmarks-jsonschema/schemas/jsck_medium-mixed/schema.json
{
  "description": "A moderately complex schema with some nesting and value constraints",
  "type": "object",
  "additionalProperties": false,
  "required": ["api_server", "transport", "storage", "chain"],
  "properties": {
    "api_server": {
      "description": "Settings for the HTTP API server",
      "type": "object",
      "additionalProperties": false,
      "required": ["url", "host", "port"],
      "properties": {
        "url": {
          "type": "string",
          "format": "uri"
        },
        "host": {
          "type": "string"
        },
        "port": {
          "type": "integer",
          "minimum": 1000
        }
      }
    },
    "transport": {
      "description": "Settings for the Redis tranport",
      "additionalProperties": false,
      "required": ["server"],
      "properties": {
        "server": {
          "type": "string"
        },
        "options": {
          "type": "object"
        },
        "queues": {
          "properties": {
            "blocking_timeout": {
              "type": "integer",
              "minimum": 0
            }
          }
        }
      }
    },
    "storage": {
      "description": "Settings for the PostgreSQL storage",
      "required": ["server", "database", "user"],
      "properties": {
        "server": {
          "type": "string"
        },
        "database": {
          "type": "string"
        },
        "user": {
          "type": "string"
        },
        "options": {
          "type": "object"
        }
      }
    },
    "chain": {
      "description": "Settings for the Chain.com client",
      "required": ["api_key_id", "api_key_secret"],
      "properties": {
        "api_key_id": {
          "type": "string"
        },
        "api_key_secret": {
          "type": "string"
        }
      }
    }
  }
}

=== katydid/paper-2027-mem-filter-benchmarks-jsonschema/schemas/example-conf-mixed/schema.json
{
	"definitions": {
		"due": {
			"type": "object",
			"anyOf": [
			{
				"properties": {
					"Year": {
						"$ref": "#/definitions/year2026"
					}
				},
				"required": ["Year"]
			},
			{
				"allOf": [                  
					{
						"properties": {
							"Year": {
								"$ref": "#/definitions/year2025"
							}
						},
						"required": ["Year"]
					},
					{
						"properties": {
							"Month": {
								"$ref": "#/definitions/month10"
							}
						},
						"required": ["Month"]
					}
				]
			}
			]
		},
		"loc": {
			"type": "object",
			"properties": {
				"Cont": {
					"$ref": "#/definitions/conteu"
				}
			},
			"required": ["Cont"]
		},
		"year2026": {
			"const": "2026"
		},
		"year2025": {
			"const": "2025"
		},
		"month10": {
			"minimum": 10
		},
		"conteu": {
			"const": "EU"
		}
	},
	"type": "object",
	"properties": {
		"Due": {
			"$ref": "#/definitions/due"
		},
		"Loc": {
			"$ref": "#/definitions/loc"
		}
	},
	"required": ["Due", "Loc"]
}
